services:
  postgres:
    container_name: postgres-sql-book
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_db
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-book
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
