services:
  postgres:
    container_name: postgres-sql-book
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresqlp/data
      POSTGRES_DB: book_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    

volumes:
  postgres:
    driver: local